### ISSUE TITLE
是否能用泛型约束呢

### ISSUE THREAD

**Issue by SeongBrave** [manfengjun/flutter_spi#1]
`class EntityFactory {
  static T generateOBJ<T>(json) {
    if (1 == 0) {
      return null;
    } else if (T.toString() == "News") {
      return News.fromJson(json) as T;
    } else {
      return null;
    }
  }
}`
这块不太友好，不知道能不能通过泛型约束搞下呢，否则整个项目中的类多了的话就麻烦了

**Comment by manfengjun** [comment]
尝试过，目前dart的泛型约束功能不完善，解析后做转换有点问题，暂时没有更好的办法

**Comment by manfengjun** [comment]
模仿Swift 的Moya实现的，dart的泛型没有swift那么好用

**Comment by manfengjun** [comment]
> `class EntityFactory { static T generateOBJ<T>(json) { if (1 == 0) { return null; } else if (T.toString() == "News") { return News.fromJson(json) as T; } else { return null; } } }`
> 这块不太友好，不知道能不能通过泛型约束搞下呢，否则整个项目中的类多了的话就麻烦了
尝试过，目前dart的泛型约束功能不完善，解析后做转换有点问题，暂时没有更好的办法,模仿Swift的Moya实现的，dart的泛型没有swift那么好用

**Comment by manfengjun** [comment]
> `class EntityFactory { static T generateOBJ<T>(json) { if (1 == 0) { return null; } else if (T.toString() == "News") { return News.fromJson(json) as T; } else { return null; } } }`
> 这块不太友好，不知道能不能通过泛型约束搞下呢，否则整个项目中的类多了的话就麻烦了


尝试过，目前dart的泛型约束功能不完善，解析后做转换有点问题，暂时没有更好的办法模仿Swift的Moya实现的，dart的泛型没有swift那么好用

**Comment by SeongBrave** [comment]
@manfengjun 嗯嗯确实，还是Swift用起来爽
